services:
  dev:
    volumes:
      - npm_cache:/home/vscode/.npm
    environment:
      NPM_CONFIG_CACHE: /home/vscode/.npm

volumes:
  npm_cache:
    external: true
    name: ${DEVCONTAINER_CACHE_PREFIX:-devcontainer}-npm-cache
